# config/meta.yml

meta_product_name: "Mercy"
meta_title: "Mercy - Play your favorite game with
non-toxic players now."
meta_description: "Find great player to play with using our in-game behavior algorithm based"
meta_image: "logo_mercy.png"
twitter_account: "@product_twitter_account"
